version: default
runtime: python27
api_version: 1
threadsafe: false
module: BigDataLabWorker

builtins:
- appstats: on
- admin_redirect: on
- remote_api: on
- deferred: on

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest

includes:
- lib/TaskWorker/TaskWorker/include.yaml
- lib/mapreduce/include.yaml

handlers:
- url: /(ad|track)/(tr|cr)\.gif
  static_files: media/ad/tr.gif
  upload: media/ad/tr.gif
  expiration: "0s"

- url: /bootstrap
  static_dir: bootstrap

- url: .*
  script: main.app
  login: admin


instance_class: B1
basic_scaling:
  max_instances: 20
  idle_timeout: 5m

skip_files:
- .*\.pyc
- .*/\.svn/.*
- .*/tests/.*
