version: 1
runtime: python27
api_version: 1
threadsafe: false
module: bigdatalab

instance_class: B8
basic_scaling:
  max_instances: 20
  idle_timeout: 5m

builtins:
- appstats: on
- admin_redirect: on
- remote_api: on
- deferred: on

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest

includes:
- lib/TaskWorker/TaskWorker/include.yaml
- lib/mapreduce/include.yaml

skip_files:
- .*\.pyc
- .*/\.svn/.*
- .*/tests/.*
- .*/\.git/.*
- .*/test/.*
